name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        env:
          TF_VAR_alarm_email: ${{ vars.ALARM_EMAIL }}
        run: terraform plan -input=false
        working-directory: ./infra

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_alarm_email: ${{ vars.ALARM_EMAIL }}
        run: terraform apply -auto-approve -input=false
        working-directory: ./infra